[[redirects]]
  # Redirecionamento para a API em desenvolvimento
  from = "/api/*"
  to = "https://backend-newsletter.onrender.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://nextlevelcodeblog.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"