# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"  # ou altere conforme a configuração de build do Next.js

[[redirects]]
  # Proxy para a API
  from = "/api/*"
  to = "https://backend-newsletter.onrender.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "https://nextlevelcodeblog.netlify.app"  # Define o domínio permitido
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Api-Key"
    X-Api-Key = "nextlevelcode"  # Adiciona sua API key no cabeçalho da requisição
    Access-Control-Allow-Credentials = "true"

[[headers]]
  # Cabeçalhos CORS para todas as rotas
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://nextlevelcodeblog.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Api-Key"
    Access-Control-Allow-Credentials = "true"

# [[redirects]]
#   # Redirecionamento de caminho antigo para novo (exemplo adicional)
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# [[redirects]]
#   # Outro redirecionamento como exemplo
#   from = "/news"
#   to = "/blog"
#   status = 301
